
#build Workflow

name: webstore-build

on:
    workflow-dispatch:
jobs:
    build:
          -name:'Build and publish'
           runs-on: ubuntu-latest

        steps:
            -name: checkout
            uses: actions/checkout@4.2.2

            -name: restore
            run: dotnet restore
              
            -name: build
            run: dotnet build--configurations release

            -name: publish
            run: dotnet publish--configuration Realse-o./webstore
